### ISSUE TITLE
Issue booting the container

### ISSUE THREAD

**Issue by mneumark** [djaydev/docker-handbrake#2]
I installed this container with the Community Applications in unRAID. I placed my GPU's UUID in the correct spot. Set my watch/output directories. Hit save. When it tries to run it I get the following error:
```
/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused "process_linux.go:432: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\n\""": unknown.
```

I have my GPU working with Plex, so I know it works elsewhere. Not sure what I'm doing wrong.

**Comment by djaydev** [comment]
The error message probably means that you have hidden spaces at the end of the UUID line "error: no cuda-capable device is detected\\n\""":"

**Comment by mneumark** [comment]
Huh. I checked, I swear there wasn't anything at the end but deleted the last character and re-entered it, and now it worked....thanks!
