### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by pgk831** [djaydev/docker-handbrake#3]
docker run -d \
    --name=handbrake \
    --runtime=nvidia \
    -p 5800:5800 \
    -p 5900:5900 \
    -v /docker/appdata/handbrake:/config:rw \
    -v $HOME:/storage:ro \
    -v $HOME/HandBrake/watch:/watch:rw \  
    -v $HOME/HandBrake/output:/output:rw \  
    -e NVIDIA_DRIVER_CAPABILITIES=all   <====  i think missing a \
    djaydev/handbrake

docker: invalid reference format: repository name must be lowercase.

**Comment by djaydev** [comment]
add the missing \
