### ISSUE TITLE
h265 10bit NVENC

### ISSUE THREAD

**Issue by repomanz** [djaydev/docker-handbrake#6]
Hello,

I see H265 NVENC available in the handbrake docker container but not 10 bit.  Is this not possible for gtx 1660?

**Comment by djaydev** [comment]
GTX 1660 does support 10 bit but unfortunately Handbrake only has NVENC without 10 bit.

**Comment by repomanz** [comment]
gotcha - so if handbrake moves to 10bit then i guess we'd be set. thanks for update.

**Comment by repomanz** [comment]
btw; do you have a recommend profile setting using nvenc that is higher quality with lower file size?

**Comment by djaydev** [comment]
> btw; do you have a recommend profile setting using nvenc that is higher quality with lower file size?

That's a broad topic. But basically to achieve higher quality with lower file size, it's mainly done with the codec you select.  Within the codec (in this case x265) all digit media works the same.  Higher quality equals higher file size, lower quality equals lower file size.  More bits used to quality, the more bits the file has that increases it's file size.

Here's how I choose the file size / quality ratio for me in Handbrake:

In Handbrake GUI video tab select Video Encoder H.265 NVenc, Profile main, and Level 5.0.

Lastly, The slider to the right of Video Encoder set to CQ: 23. 

With hardware encoding you lose a bit of quality, so if those settings don't look good to you in the new video, slide CQ:22 and on down until you're happy with the quality.

**Comment by repomanz** [comment]
what is level 5? slow?

**Comment by djaydev** [comment]
> what is level 5? slow?

That's getting more into Handbrake itself.  I've read about all the settings years and years ago but I can't help with anything past the docker image itself.  

You can check out Handbrake's docs here https://handbrake.fr/docs/en/latest/
