### ISSUE TITLE
Server disconnect error code 1006

### ISSUE THREAD

**Issue by leprechaun17** [djaydev/docker-handbrake#7]
Just upgraded to Unraid version 6.9.1. Docker is loading properly with no errors but I am getting a Server disconnect error code 1006 when loading Handbrake in Chrome GUI. Any ideas?
Here is the container log for additional information.
ErrorWarningSystemArrayLogin

[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] 95-check-optical-drive.sh: executing...
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: no usable optical drive found.
[cont-init.d] 95-check-optical-drive.sh: exited 0.
[cont-init.d] 95-check-qsv.sh: executing...
[cont-init.d] 95-check-qsv.sh: Processor: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
[cont-init.d] 95-check-qsv.sh: Intel Quick Sync Video not supported: device directory /dev/dri not exposed to the container.
[cont-init.d] 95-check-qsv.sh: exited 0.
[cont-init.d] handbrake.sh: executing...
[cont-init.d] handbrake.sh: core dump file location: core
[cont-init.d] handbrake.sh: core dump file size: (blocks)
[cont-init.d] handbrake.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[nginx] starting...
[services.d] starting autovideoconverter...
[certsmonitor] disabling service: secure connection not enabled.
[services.d] starting xvfb...
./run: 10: ./run: ps: not found
[xvfb] starting...
[autovideoconverter] starting...
[autovideoconverter] Processing watch folder '/watch'...
[autovideoconverter] Watch folder '/watch' processing terminated.
[services.d] starting logmonitor...
[logmonitor] no file to monitor: disabling service...
s6-svwait: fatal: timed out
[services.d] starting statusmonitor...
[services.d] starting openbox...
[statusmonitor] no file to monitor: disabling service...
[openbox] starting...
[services.d] starting x11vnc...
[x11vnc] starting...
10/03/2021 23:14:42 passing arg to libvncserver: -rfbport
10/03/2021 23:14:42 passing arg to libvncserver: 5900
10/03/2021 23:14:42 passing arg to libvncserver: -rfbportv6
10/03/2021 23:14:42 passing arg to libvncserver: -1
10/03/2021 23:14:42 passing arg to libvncserver: -httpportv6
10/03/2021 23:14:42 passing arg to libvncserver: -1
10/03/2021 23:14:42 passing arg to libvncserver: -desktop
10/03/2021 23:14:42 passing arg to libvncserver: HandBrake
10/03/2021 23:14:42 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 2027

10/03/2021 23:14:42 Using X display :0
10/03/2021 23:14:42 rootwin: 0x388 reswin: 0x400001 dpy: 0xd0d724f0
10/03/2021 23:14:42
10/03/2021 23:14:42 ------------------ USEFUL INFORMATION ------------------
[services.d] starting app...
[app] starting HandBrake...
10/03/2021 23:14:42 X DAMAGE available on display, using it for polling hints.
10/03/2021 23:14:42 To disable this behavior use: '-noxdamage'
10/03/2021 23:14:42
10/03/2021 23:14:42 Most compositing window managers like 'compiz' or 'beryl'
10/03/2021 23:14:42 cause X DAMAGE to fail, and so you may not see any screen
10/03/2021 23:14:42 updates via VNC. Either disable 'compiz' (recommended) or
10/03/2021 23:14:42 supply the x11vnc '-noxdamage' command line option.
10/03/2021 23:14:42 X COMPOSITE available on display, using it for window polling.
10/03/2021 23:14:42 To disable this behavior use: '-noxcomposite'
10/03/2021 23:14:42
10/03/2021 23:14:42 Wireframing: -wireframe mode is in effect for window moves.
10/03/2021 23:14:42 If this yields undesired behavior (poor response, painting
10/03/2021 23:14:42 errors, etc) it may be disabled:
10/03/2021 23:14:42 - use '-nowf' to disable wireframing completely.
10/03/2021 23:14:42 - use '-nowcr' to disable the Copy Rectangle after the
10/03/2021 23:14:42 moved window is released in the new position.
10/03/2021 23:14:42 Also see the -help entry for tuning parameters.
10/03/2021 23:14:42 You can press 3 Alt_L's (Left "Alt" key) in a row to
10/03/2021 23:14:42 repaint the screen, also see the -fixscreen option for
10/03/2021 23:14:42 periodic repaints.
10/03/2021 23:14:42 GrabServer control via XTEST.
10/03/2021 23:14:42
10/03/2021 23:14:42 Scroll Detection: -scrollcopyrect mode is in effect to
10/03/2021 23:14:42 use RECORD extension to try to detect scrolling windows
10/03/2021 23:14:42 (induced by either user keystroke or mouse input).

10/03/2021 23:14:42 If this yields undesired behavior (poor response, painting
10/03/2021 23:14:42 errors, etc) it may be disabled via: '-noscr'
10/03/2021 23:14:42 Also see the -help entry for tuning parameters.
10/03/2021 23:14:42 You can press 3 Alt_L's (Left "Alt" key) in a row to
10/03/2021 23:14:42 repaint the screen, also see the -fixscreen option for
10/03/2021 23:14:42 periodic repaints.
10/03/2021 23:14:42
10/03/2021 23:14:42 XKEYBOARD: number of keysyms per keycode 7 is greater
10/03/2021 23:14:42 than 4 and 51 keysyms are mapped above 4.
10/03/2021 23:14:42 Automatically switching to -xkb mode.
10/03/2021 23:14:42 If this makes the key mapping worse you can
10/03/2021 23:14:42 disable it with the "-noxkb" option.
10/03/2021 23:14:42 Also, remember "-remap DEAD" for accenting characters.
10/03/2021 23:14:42
10/03/2021 23:14:42 X FBPM extension not supported.
Xlib: extension "DPMS" missing on display ":0".
10/03/2021 23:14:42 X display is not capable of DPMS.
10/03/2021 23:14:42 --------------------------------------------------------
10/03/2021 23:14:42
10/03/2021 23:14:42 Default visual ID: 0x21
[services.d] done.
10/03/2021 23:14:42 Read initial data from X display into framebuffer.
10/03/2021 23:14:42 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
10/03/2021 23:14:42
10/03/2021 23:14:42 X display :0 is 32bpp depth=24 true color
10/03/2021 23:14:42
10/03/2021 23:14:42 Listening for VNC connections on TCP port 5900
10/03/2021 23:14:42
10/03/2021 23:14:42 Xinerama is present and active (e.g. multi-head).
10/03/2021 23:14:42 Xinerama: number of sub-screens: 1
10/03/2021 23:14:42 Xinerama: no blackouts needed (only one sub-screen)
10/03/2021 23:14:42
10/03/2021 23:14:42 fb read rate: 411 MB/sec
10/03/2021 23:14:42 fast read: reset -wait ms to: 10
10/03/2021 23:14:42 fast read: reset -defer ms to: 10
10/03/2021 23:14:42 The X server says there are 10 mouse buttons.

10/03/2021 23:14:42 screen setup finished.
10/03/2021 23:14:42

The VNC desktop is: 0541ade23f5c:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

** Message: 23:14:42.474: Couldn't initialize gstreamer. Disabling live preview.
10/03/2021 23:14:43 Got connection from client 127.0.0.1
10/03/2021 23:14:43 other clients:
10/03/2021 23:14:43 Got 'ws' WebSockets handshake
10/03/2021 23:14:43 - webSocketsHandshake: using base64 encoding
10/03/2021 23:14:43 - WebSockets client version hybi-13

caught signal: 11
10/03/2021 23:14:43 deleted 40 tile_row polling images.
[x11vnc] starting...
10/03/2021 23:14:43 passing arg to libvncserver: -rfbport
10/03/2021 23:14:43 passing arg to libvncserver: 5900
10/03/2021 23:14:43 passing arg to libvncserver: -rfbportv6
10/03/2021 23:14:43 passing arg to libvncserver: -1
10/03/2021 23:14:43 passing arg to libvncserver: -httpportv6
10/03/2021 23:14:43 passing arg to libvncserver: -1
10/03/2021 23:14:43 passing arg to libvncserver: -desktop
10/03/2021 23:14:43 passing arg to libvncserver: HandBrake
10/03/2021 23:14:43 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 2078

10/03/2021 23:14:43 Using X display :0
10/03/2021 23:14:43 rootwin: 0x388 reswin: 0x400001 dpy: 0x4d80c4f0
10/03/2021 23:14:43
10/03/2021 23:14:43 ------------------ USEFUL INFORMATION ------------------
10/03/2021 23:14:43 X DAMAGE available on display, using it for polling hints.
10/03/2021 23:14:43 To disable this behavior use: '-noxdamage'
10/03/2021 23:14:43
10/03/2021 23:14:43 Most compositing window managers like 'compiz' or 'beryl'
10/03/2021 23:14:43 cause X DAMAGE to fail, and so you may not see any screen
10/03/2021 23:14:43 updates via VNC. Either disable 'compiz' (recommended) or
10/03/2021 23:14:43 supply the x11vnc '-noxdamage' command line option.
10/03/2021 23:14:43 X COMPOSITE available on display, using it for window polling.
10/03/2021 23:14:43 To disable this behavior use: '-noxcomposite'
10/03/2021 23:14:43
10/03/2021 23:14:43 Wireframing: -wireframe mode is in effect for window moves.
10/03/2021 23:14:43 If this yields undesired behavior (poor response, painting
10/03/2021 23:14:43 errors, etc) it may be disabled:
10/03/2021 23:14:43 - use '-nowf' to disable wireframing completely.
10/03/2021 23:14:43 - use '-nowcr' to disable the Copy Rectangle after the
10/03/2021 23:14:43 moved window is released in the new position.
10/03/2021 23:14:43 Also see the -help entry for tuning parameters.
10/03/2021 23:14:43 You can press 3 Alt_L's (Left "Alt" key) in a row to
10/03/2021 23:14:43 repaint the screen, also see the -fixscreen option for
10/03/2021 23:14:43 periodic repaints.
10/03/2021 23:14:43 GrabServer control via XTEST.
10/03/2021 23:14:43
10/03/2021 23:14:43 Scroll Detection: -scrollcopyrect mode is in effect to
10/03/2021 23:14:43 use RECORD extension to try to detect scrolling windows
10/03/2021 23:14:43 (induced by either user keystroke or mouse input).

10/03/2021 23:14:43 If this yields undesired behavior (poor response, painting
10/03/2021 23:14:43 errors, etc) it may be disabled via: '-noscr'
10/03/2021 23:14:43 Also see the -help entry for tuning parameters.
10/03/2021 23:14:43 You can press 3 Alt_L's (Left "Alt" key) in a row to
10/03/2021 23:14:43 repaint the screen, also see the -fixscreen option for
10/03/2021 23:14:43 periodic repaints.
10/03/2021 23:14:43
10/03/2021 23:14:43 XKEYBOARD: number of keysyms per keycode 7 is greater
10/03/2021 23:14:43 than 4 and 51 keysyms are mapped above 4.
10/03/2021 23:14:43 Automatically switching to -xkb mode.
10/03/2021 23:14:43 If this makes the key mapping worse you can
10/03/2021 23:14:43 disable it with the "-noxkb" option.
10/03/2021 23:14:43 Also, remember "-remap DEAD" for accenting characters.
10/03/2021 23:14:43
10/03/2021 23:14:43 X FBPM extension not supported.
Xlib: extension "DPMS" missing on display ":0".
10/03/2021 23:14:43 X display is not capable of DPMS.
10/03/2021 23:14:43 --------------------------------------------------------
10/03/2021 23:14:43
10/03/2021 23:14:43 Default visual ID: 0x21
10/03/2021 23:14:43 Read initial data from X display into framebuffer.
10/03/2021 23:14:43 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
10/03/2021 23:14:43
10/03/2021 23:14:43 X display :0 is 32bpp depth=24 true color
10/03/2021 23:14:43
10/03/2021 23:14:43 Listening for VNC connections on TCP port 5900
10/03/2021 23:14:43
10/03/2021 23:14:43 Xinerama is present and active (e.g. multi-head).
10/03/2021 23:14:43 Xinerama: number of sub-screens: 1
10/03/2021 23:14:43 Xinerama: no blackouts needed (only one sub-screen)
10/03/2021 23:14:43
10/03/2021 23:14:43 fb read rate: 1282 MB/sec
10/03/2021 23:14:43 fast read: reset -wait ms to: 10
10/03/2021 23:14:43 fast read: reset -defer ms to: 10
10/03/2021 23:14:43 The X server says there are 10 mouse buttons.

10/03/2021 23:14:43 screen setup finished.
10/03/2021 23:14:43

The VNC desktop is: 0541ade23f5c:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

10/03/2021 23:14:45 Got connection from client 127.0.0.1
10/03/2021 23:14:45 other clients:
10/03/2021 23:14:45 Got 'ws' WebSockets handshake
10/03/2021 23:14:45 - webSocketsHandshake: using base64 encoding
10/03/2021 23:14:45 - WebSockets client version hybi-13

caught signal: 11
10/03/2021 23:14:45 deleted 40 tile_row polling images.
[x11vnc] starting...
10/03/2021 23:14:45 passing arg to libvncserver: -rfbport
10/03/2021 23:14:45 passing arg to libvncserver: 5900
10/03/2021 23:14:45 passing arg to libvncserver: -rfbportv6
10/03/2021 23:14:45 passing arg to libvncserver: -1
10/03/2021 23:14:45 passing arg to libvncserver: -httpportv6
10/03/2021 23:14:45 passing arg to libvncserver: -1
10/03/2021 23:14:45 passing arg to libvncserver: -desktop
10/03/2021 23:14:45 passing arg to libvncserver: HandBrake
10/03/2021 23:14:45 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 2092

10/03/2021 23:14:45 Using X display :0
10/03/2021 23:14:45 rootwin: 0x388 reswin: 0x400001 dpy: 0x987634f0
10/03/2021 23:14:45
10/03/2021 23:14:45 ------------------ USEFUL INFORMATION ------------------
10/03/2021 23:14:45 X DAMAGE available on display, using it for polling hints.
10/03/2021 23:14:45 To disable this behavior use: '-noxdamage'
10/03/2021 23:14:45
10/03/2021 23:14:45 Most compositing window managers like 'compiz' or 'beryl'
10/03/2021 23:14:45 cause X DAMAGE to fail, and so you may not see any screen
10/03/2021 23:14:45 updates via VNC. Either disable 'compiz' (recommended) or
10/03/2021 23:14:45 supply the x11vnc '-noxdamage' command line option.
10/03/2021 23:14:45 X COMPOSITE available on display, using it for window polling.
10/03/2021 23:14:45 To disable this behavior use: '-noxcomposite'
10/03/2021 23:14:45
10/03/2021 23:14:45 Wireframing: -wireframe mode is in effect for window moves.
10/03/2021 23:14:45 If this yields undesired behavior (poor response, painting
10/03/2021 23:14:45 errors, etc) it may be disabled:
10/03/2021 23:14:45 - use '-nowf' to disable wireframing completely.
10/03/2021 23:14:45 - use '-nowcr' to disable the Copy Rectangle after the
10/03/2021 23:14:45 moved window is released in the new position.
10/03/2021 23:14:45 Also see the -help entry for tuning parameters.
10/03/2021 23:14:45 You can press 3 Alt_L's (Left "Alt" key) in a row to
10/03/2021 23:14:45 repaint the screen, also see the -fixscreen option for
10/03/2021 23:14:45 periodic repaints.
10/03/2021 23:14:45 GrabServer control via XTEST.
10/03/2021 23:14:45
10/03/2021 23:14:45 Scroll Detection: -scrollcopyrect mode is in effect to
10/03/2021 23:14:45 use RECORD extension to try to detect scrolling windows
10/03/2021 23:14:45 (induced by either user keystroke or mouse input).

10/03/2021 23:14:45 If this yields undesired behavior (poor response, painting
10/03/2021 23:14:45 errors, etc) it may be disabled via: '-noscr'
10/03/2021 23:14:45 Also see the -help entry for tuning parameters.
10/03/2021 23:14:45 You can press 3 Alt_L's (Left "Alt" key) in a row to
10/03/2021 23:14:45 repaint the screen, also see the -fixscreen option for
10/03/2021 23:14:45 periodic repaints.
10/03/2021 23:14:45
10/03/2021 23:14:45 XKEYBOARD: number of keysyms per keycode 7 is greater
10/03/2021 23:14:45 than 4 and 51 keysyms are mapped above 4.
10/03/2021 23:14:45 Automatically switching to -xkb mode.
10/03/2021 23:14:45 If this makes the key mapping worse you can
10/03/2021 23:14:45 disable it with the "-noxkb" option.
10/03/2021 23:14:45 Also, remember "-remap DEAD" for accenting characters.
10/03/2021 23:14:45
10/03/2021 23:14:45 X FBPM extension not supported.
Xlib: extension "DPMS" missing on display ":0".
10/03/2021 23:14:45 X display is not capable of DPMS.
10/03/2021 23:14:45 --------------------------------------------------------
10/03/2021 23:14:45
10/03/2021 23:14:45 Default visual ID: 0x21
10/03/2021 23:14:45 Read initial data from X display into framebuffer.
10/03/2021 23:14:45 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
10/03/2021 23:14:45
10/03/2021 23:14:45 X display :0 is 32bpp depth=24 true color
10/03/2021 23:14:45
10/03/2021 23:14:45 Listening for VNC connections on TCP port 5900
10/03/2021 23:14:45
10/03/2021 23:14:45 Xinerama is present and active (e.g. multi-head).
10/03/2021 23:14:45 Xinerama: number of sub-screens: 1
10/03/2021 23:14:45 Xinerama: no blackouts needed (only one sub-screen)
10/03/2021 23:14:45
10/03/2021 23:14:45 fb read rate: 1317 MB/sec
10/03/2021 23:14:45 fast read: reset -wait ms to: 10
10/03/2021 23:14:45 fast read: reset -defer ms to: 10
10/03/2021 23:14:45 The X server says there are 10 mouse buttons.

10/03/2021 23:14:45 screen setup finished.
10/03/2021 23:14:45

The VNC desktop is: 0541ade23f5c:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

**Comment by whoopn** [comment]
This is just chrome...they're blocking ports other than 80 due to the NAT slipstreaming attack, use another browser.
